### ISSUE TITLE
what's wrong with ngx.sleep when using resty.lock() in concurrency scene

### ISSUE THREAD

**Issue by foolslove** [openresty/lua-resty-lock#17]
## error.log:
[error] 870#870: *4018 failed to run balancer_by_lua*: ...xxx-apigateway/openresty/nginx//../lualib/resty/lock.lua:151: API disabled in the context of balancer_by_lua*
stack traceback:
	[C]: in function 'sleep'
	...xxx-apigateway/openresty/nginx//../lualib/resty/lock.lua:151: in function 'lock'
	...ay/openresty/nginx//luaext/core/circuitbreaker_cache.lua:68: in function 'compare_and_set'

**Comment by agentzh** [comment]
@foolslove I think the error message is self-explanatory. The balancer_by_lua* context does not allow Lua APIs that could *yield*. Try an earlier phase handler that supports yielding instead, like `access_by_lua*` and `rewrite_by_lua*`.

**Comment by foolslove** [comment]
many thanks
