### ISSUE TITLE
Test cases failing on rhel 7.6 ppc64le - Getting errors "ngx_slab_alloc() failed: no memory"

### ISSUE THREAD

**Issue by SantoshMagdum** [openresty/lua-resty-lock#25]
Hi All,

I had build the nginx binary on rhel 7.6 ppc64le (version 1.17.1.1rc0) from source code -  https://github.com/openresty/openresty.
Please note that, I had copied and used ppc64le compiled LuaJIT code while building openresty (nginx).
Below command I used to compile the openresty -
	
	
./configure --with-cc-opt="-DNGX_LUA_USE_ASSERT -DNGX_LUA_ABORT_AT_PANIC" --with-http_image_filter_module --with-http_dav_module  --with-http_auth_request_module --with-poll_module --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_ssl_module --with-http_iconv_module  --with-http_drizzle_module --with-http_postgres_module --with-http_addition_module --add-module=/usr/openresty/openresty_test_modules/nginx-eval-module --add-module=/usr/openresty/openresty_test_modules/replace-filter-nginx-module

And then tried to execute the test cases for 'lua-resty-lock' like below -

[root]# pwd
/usr/openresty/openresty/openresty-1.17.1.1rc0/build/lua-resty-lock-0.08
[root]# prove -r t

NOTE: The 'lua-resty-lock-0.08' version downloaded with openresty bundle is 0.08.

But I am getting below kind of repeated errors -
			
		nginx: [crit] ngx_slab_alloc() failed: no memory
		nginx: [crit] ngx_slab_alloc() failed: no memory
		nginx: [crit] ngx_slab_alloc() failed: no memory
		nginx: [crit] ngx_slab_alloc() failed: no memory

Please help suggest if I need to export any specific environment/setup any additional service or should try any compiler flag/somehow increase timeout value to make these test cases pass?

nginx version (compiled with libdrizzle 1.0 and radius, mariadb, postgresql services setup) -

	# nginx -V
	nginx version: openresty/1.17.1.1rc0
	built by gcc 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)
	built with OpenSSL 1.0.2k-fips  26 Jan 2017
	TLS SNI support enabled
	configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt='-O2 -DNGX_LUA_USE_ASSERT -DNGX_LUA_ABORT_AT_PANIC' --add-module=../ngx_devel_kit-0.3.1rc1 --add-module=../iconv-nginx-module-0.14 --add-module=../echo-nginx-module-0.61 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.32 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.08 --add-module=../drizzle-nginx-module-0.1.11 --add-module=../ngx_postgres-1.0 --add-module=../srcache-nginx-module-0.31 --add-module=../ngx_lua-0.10.15 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.15 --add-module=../rds-csv-nginx-module-0.09 --add-module=../ngx_stream_lua-0.0.7 --with-ld-opt=-Wl,-rpath,/usr/local/openresty/luajit/lib --with-http_image_filter_module --with-http_dav_module --with-http_auth_request_module --with-poll_module --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_ssl_module --with-http_addition_module --add-module=/usr/openresty/openresty_test_modules/nginx-eval-module --add-module=/usr/openresty/openresty_test_modules/replace-filter-nginx-module --with-stream --with-stream_ssl_preread_module

**Comment by agentzh** [comment]
@SantoshMagdum What's the memory page size on that system? Our test cases assume a 4KB page size generally.

**Comment by SantoshMagdum** [comment]
@agentzh , Thanks for quick reply.
It seems liked we have 6KB page size
       getconf PAGESIZE
       65536

**Comment by SantoshMagdum** [comment]
@agentzh 
I had increased the lua shared memory zone size from 100k to 200k in file 't/sanity.t'.
Thus modified file "lua-resty-lock-0.08/t/sanity.t", to update parameter 'lua_shared_dict' to -
                lua_shared_dict cache_locks 200k;
from original value
                lua_shared_dict cache_locks 100k;

With this change the test cases running successfully.

        [root@ lua-resty-lock-0.08]# prove -r t/
        t/sanity.t .. ok
        All tests successful.
        Files=1, Tests=84,  9 wallclock secs ( 0.03 usr  0.01 sys +  0.59 cusr  0.22 csys =  0.85 CPU)
        Result: PASS
        [root@ lua-resty-lock-0.08]# 

Please suggest should I make this change and share merge request?

**Comment by SantoshMagdum** [comment]
I shall commit the code changes and raise PR soon. 
Closing this open issue.
