### ISSUE TITLE
What happens across a fork?

### ISSUE THREAD

**Issue by nelson2005** [openresty/lua-resty-lock#4]
My code looks a like this, is it correct?  Does the forked lock need any special handling?

```lua
local lock = resty_lock:new('my_lock')
local elapsed, errmsg = lock:lock(key)
local pid, error = posix.fork()
if pid == 0 then -- child- should child unlock the lock?
   posix.exec('/path/to/program')
else  -- parent
  lock:unlock()
end
```

**Comment by agentzh** [comment]
@nelson2005 First of all, I must say that it's not recommended to fork in nginx workers. Try using some alternatives like lua-resty-shell:

https://github.com/juce/lua-resty-shell

Regarding your usage, lua-resty-lock stores the lock state in the shared memory zones (shared by all the nginx workers and other forked sub-processes). So it does not need special handling to my knowledge. You can always run some delibrate test cases yourself anyway.

**Comment by nelson2005** [comment]
thanks.  I looked at lua-resty-shell, but having to run another daemon seemed a little burdensome.  I didn't see anything else on the net that looked very useful.

I did do some tests and didn't see any bad results.  I'll check back if I see any issues.
